version: '3.5'
services:
  
  cadpublish-app:
    container_name: cadpublish-app
    image: jbuchbinder/cadpublish
    restart: always
    volumes:
      - ./cadpublish.yaml:/app/config.yaml:ro

  cadpublish-shell:
    container_name: cadpublish-shell
    image: chromedp/headless-shell
    ports:
      - "9222:9222"